#CodeAssist project settings
#Tue Sep 22 09:27:05 GMT+05:00 2026
tree.expanded.Project=root\:/storage/emulated/0/Android/data/com.tyron.code/files/codeassist/projects/Flux/app/src/main/java\nroot\:/storage/emulated/0/Android/data/com.tyron.code/files/codeassist/projects/Flux/app/src/main/assets\nmodule\:app\nroot\:/storage/emulated/0/Android/data/com.tyron.code/files/codeassist/projects/Flux/app/src/main/res\nworkspace
tree.expanded.AllFiles=workspace
